#index:
#    path: /
#    controller: App\Controller\DefaultController::index


test:
   path: /test
   controller: App\Controller\TestController::index


user:
   path: /user/{name}
   controller: App\Controller\TestController::displayUser
   defaults:
    name: "Marry"

# testvare:
#    path: /testvare
#    controller: App\Controller\TestController::testVareAction
